import json
import re

# Comprehensive mapping for Japanese and English design terms to Korean
TRANSLATION_MAP = {
    # Headers & Basic Terms
    "全体デザイン設定": "전체 디자인 설정",
    "トーン": "톤",
    "ビジュアル・アイデンティティ": "비주얼 아이덴티티",
    "背景色": "배경색",
    "文字色": "글자색",
    "アクセントカラー": "강조색",
    "画像スタイル": "이미지 스타일",
    "特徴": "특징",
    "イメージャリ": "이미지",
    
    # English Adjectives/Nouns (Legacy & New)
    "Creative": "창의적",
    "Rough": "러프한",
    "Personal": "개인적",
    "Brainstorming": "브레인스토밍",
    "Authentic": "진정성 있는",
    "Friendly": "친근한",
    "Professional": "전문적",
    "Trustworthy": "신뢰할 수 있는",
    "Modern": "모던한",
    "Inclusive": "포용적",
    "Clear": "명확한",
    "Playful": "유쾌한",
    "Information": "정보 중심",
    "Girly": "에너제틱 소녀감성",
    "Love": "사랑스러운",
    "Dream": "몽환적",
    "Sparkle": "반짝이는",
    "Shojo Manga": "순정만화 스타일",
    "Isometric": "아이소메트릭",
    "Colorful": "다채로운",
    "High Impact": "강렬한 임팩트",
    "Structure": "구조적",
    "Context": "맥락 중심",
    "Data": "데이터 중심",
    "Focus": "집중",
    "Minimal": "미니멀",
    "Tech": "테크놀로지",
    "Future": "미래지향적",
    "Nature": "자연주의",
    "Brand": "브랜드 아이덴티티",
    "Opening": "오프닝",
    "Emotional": "감성적",
    "Spark": "영감",
    "Agenda": "목차/아젠다",
    "Evidence": "증거/팩트",
    "Conclusion": "결론",
    "Ethos": "신뢰/권위",
    "Action": "행동유도",
    "Casual": "캐주얼",
    "Chalk": "분필",
    "Handwritten": "손글씨",
    "Clay": "점토",
    "Stopmotion": "스톱모션",
    "Cute": "귀여운",
    "Line": "선",
    "White": "화이트",
    "Tilt-shift": "틸트 시프트",
    "Miniature": "미니어처",
    "Blur": "흐림",
    "Blueprint": "청사진",
    "Architecture": "건축",
    "Blue": "블루",
    "Vector art": "벡터 아트",
    "Monochrome": "모노크롬",
    "Line Art": "라인 아트",
    "Watercolor": "수채화",
    "Map": "지도",
    "Fantasy": "판타지",
    "Material design": "머티리얼 디자인",
    "Ukiyo-e": "우키요에",
    "Art Deco": "아르 데코",
    "Foil": "포일",
    "Neon Noir": "네온 누아르",
    "Calligraphy": "서예",
    "Ink Wash": "수묵화",
    "Leaf": "잎",
    "Tattoo": "타투",
    "Risograph": "리소그래프",
    "Noise": "노이즈",
    "Marble": "대리석",
    "Neumorphism": "뉴모피즘",
    "Soft": "부드러운",
    "Form": "형태",
    "Shadow": "그림자",
    "Light": "빛",
    "Black&White": "흑백",
    "Portrait": "초상화",
    "Glow": "발광",
    "Night": "밤",
    "Rain": "비",
    "Lofi": "로파이",
    "Grain": "그레인",
    "Geometric Abstraction": "기하학적 추상",
    "Bauhaus": "바우하우스",
    "Cyberpunk": "사이버펑크",
    "Circuit": "회로",
    "Hologram": "홀로그램",
    "UI": "UI",
    "Technical": "기술적",
    "Cyanotype": "청사진(시아노타입)",
    "Grid": "그리드",
    "Industrial": "산업용",
    "Orange": "오렌지",
    "Ghost": "유령",
    "Mediterranean": "지중해",
    "Tile": "타일",
    "Underwater": "수중",
    "Low Poly": "로우 폴리",
    "Water": "물",
    "Frutiger Aero": "프루티거 에어로",
    "Glass": "유리",
    "Y2K": "Y2K",
    "Chrome": "크롬",
    "Liquid metal": "액체 금속",
    "Fluid": "유동적",
    "Dark Mode": "다크 모드",
    "Paper Cutout": "종이 오리기",
    "Shadow box": "섀도우 박스",
    "Pastel": "파스텔",
    "Paper": "종이",
    "Texture": "텍스처",
    "Paper Craft": "페이퍼 크래프트",
    "Layered": "레이어드",
    "Newspaper": "신문",
    "Blackletter": "블랙레터",
    "Red": "레드",
    "Constructivism": "구조주의",
    "Propaganda": "선전",
    "Hacker": "해커",
    "Terminal": "터미널",
    "Autumn": "가을",
    "Sunlight": "햇살",
    "Forest": "숲",
    "Green": "그린",
    "Coding": "코딩",
    "Monospace": "고정폭 글꼴",
    "Scandinavian": "스칸디나비아",
    "Zen": "젠(선)",
    "Stone": "돌",
    "Japanese Zen": "일본식 젠",
    "Moss": "이끼",
    "Celtic": "켈트",
    "Knot": "매듭",
    "Gothic": "고딕",
    "Stained Glass": "스테인드글라스",
    "Dark": "다크",
    "Religious": "종교적",
    "Oil painting": "유화",
    "Impasto": "임파스토",
    "Classical": "클래식",
    "Glassmorphism": "글래스모피즘",
    "3D Type": "3D 타입",
    "Plastic": "플라스틱",
    "Game": "게임",
    "Web3": "웹3",
    "Fintech Landing": "핀테크 랜딩",
    "High-Tech": "하이테크",
    "Masterpiece": "걸작",
    "Surrealist Dream": "초현실적 꿈",
    "Uncanny": "기이한",
    "Deep Texture": "깊은 질감",
    "Grid": "그리드",
    "Pure": "순수",
    "Glamour": "글래머",
    "Luxury": "럭셔리",
    "Aerodynamic": "공기역학적",
    "Organic Textile": "유기적 직물",
    "Craft": "공예",
    "Warm Historicity": "따뜻한 역사성",
    "Luminous Layer": "빛나는 레이어",
    "Painterly": "회화적",
    "Burnished Gold": "윤기 나는 금",
    "Divine": "신성한",
    "Opulent Filigree": "화려한 세공",
    "Apollo Tech": "아폴로 테크",
    "Lunar": "달",
    "Cosmic Functionalism": "우주적 기능주의",
    "Constructivist Red": "구조주의 레드",
    "Bold": "대담한",
    "Industrial Revolution": "산업 혁명",
    "Cold War Surveillance": "냉전 감시",
    "Binary": "이진법",
    "Brutalist Concrete": "브루탈리즘 콘크리트",
    "Vaporwave UI": "베이퍼웨이브 UI",
    "90s Retro": "90년대 레트로",
    "Neon Grid": "네온 그리드",
    "Cyberpunk HUD": "사이버펑크 HUD",
    "Neon City": "네온 시티",
    "Layered Metal": "레이어드 메탈",
    "Swiss Modernism": "스위스 모더니즘",
    "Grid System": "그리드 시스템",
    "Bold Primary": "대담한 원색",
    "Ghibli Scenic": "지브리 풍경",
    "Golden Hour": "골든 아워",
    "Bauhaus Rational": "바우하우스 합리주의",
    "Primary Geometry": "기초 기하학",
    "Steel & Glass": "강철과 유리",
    "Zaha Fluid": "자하 하디드 유체",
    "Parametric": "파라메트릭",
    "Seamless High-Gloss": "이음새 없는 고광택",
    "Hanok Zen": "한옥 젠",
    "Traditional Korean": "한국 전통",
    "Paper & Wood": "종이와 나무",
    "Napa Vineyard": "나파 포도원",
    "Terracotta": "테라코타",
    "Oak & Vine": "참나무와 덩굴",
    "Bioluminescent Deep": "심해 발광",
    "Indigo": "인디고",
    "Neon Organic": "네온 유기체",
    "Hygge Interior": "휘게 인테리어",
    "Scandi": "스칸디",
    "Warm Light": "따뜻한 빛",
    "Wabi-Sabi": "와비사비",
    "Imperfect": "불완전함",
    "Zen Stone": "젠 스톤",
    "African Tribal": "아프리카 부족",
    "Rhythmic": "리듬감 있는",
    "Mudcloth Texture": "머드클로스 질감",
    "Victorian Gothic": "빅토리안 고딕",
    "Ornate": "장식적인",
    "Crimson Velvet": "진홍색 벨벳",
    "Neo-Brutalist UI": "네오 브루탈리즘 UI",
    "Gritty": "거친",
    "High-Contrast Neon": "고대비 네온",
    "Tropical Botanic": "열대 식물",
    "Lush": "우거진",
    "Scientific Ink": "과학적 잉크",
    "Space-Age Retro": "스페이스 에이지 레트로",
    "Atomic Future": "원자력 미래",
    "Glacial Antarctica": "남극 빙하",
    "Crystalline": "결정체",
    "Deep Cyan": "깊은 시안색",
    "Santorini Breezy": "산토리니 산들바람",
    "White Stucco": "흰색 스투코",
    "Aegean Blue": "에게해 블루",
    "Steampunk Factory": "스팀펑크 공장",
    "Copper Brass": "구리와 황동",
    "Steam Punk": "스팀 펑크",
    "Desert Oasis": "사막 오아시스",
    "Mid-Century": "미드 센추리",
    "Sage & Terracotta": "세이지와 테라코타",
    "Akihabara Neon": "아키하바라 네온",
    "Cyber-Street": "사이버 거리",
    "Rainy Midnight": "비 오는 자정",
    "Bioluminescent Forest": "발광 숲",
    "Avatar": "아바타",
    "Neon Teal": "네온 청록색",
    "Himalayan Temple": "히말라야 사원",
    "Stone Fog": "돌 안개",
    "Yak Butter Zen": "야크 버터 젠",
    "Nordic Noir": "노르딕 누아르",
    "Melancholy": "우울함",
    "Steel Lake": "강철 호수",
    "Ancient Mayan": "고대 마야",
    "Geometric Stone": "기하학적 돌",
    "Cinnabar Red": "진사색",
    "Space Colony Green": "우주 식민지 녹색",
    "Hydroponics": "수경 재배",
    "Clinical White": "임상적인 흰색",
    "Abyssal Vents": "심해 열수구",
    "Volcanic Ocean": "화산 바다",
    "Magma Red": "마그마 레드",
    "Imperial Palace": "황궁",
    "Royal Malachite": "로열 말라카이트",
    "Winter Grandeur": "겨울의 웅장함",
    "Bio-Hacking UI": "바이오 해킹 UI",
    "Organic Fusion": "유기적 융합",
    "Neural Blue": "신경 블루",
    "Magma Obsidian": "마그마 흑요석",
    "Volcanic Cave": "화산 동굴",
    "Internal Glow": "내부 발광",
    "Ether-punk": "에테르 펑크",
    "Cloud City": "클라우드 시티",
    "Victorian Flight": "빅토리안 비행",
    "Acid Corrosion": "산 부식",
    "Industrial Decay": "산업 붕괴",
    "Toxic Sludge": "유독성 슬러지",
    "Digital Mirage": "디지털 신기루",
    "Holographic Oasis": "홀로그래픽 오아시스",
    "Data Palm": "데이터 야자수",
    "Zen-Cyberpunk": "젠 사이버펑크",
    "Kyoto Future": "교토의 미래",
    "Sakura LED": "벚꽃 LED",
    "Macro Chitin": "매크로 키틴",
    "Insect Armor": "곤충 갑옷",
    "Iridescent Shell": "무지개빛 껍질",
    "Quantum Realm": "양자 영역",
    "Subatomic Vibrations": "아원자 진동",
    "Fractal Energy": "프랙탈 에너지",
    "Martian Outpost": "화성 전초기지",
    "Red Dust": "붉은 먼지",
    "Sun-scorched Metal": "태양에 그을린 금속",
    "Gothic Lolita": "고딕 롤리타",
    "Porcelain Lace": "도자기 레이스",
    "Dark Romance": "다크 로맨스",
    "Solarpunk Farm": "솔라펑크 농장",
    "Bio-Reactor": "바이오 리액터",
    "Glass & Algae": "유리와 조류",
    "Film Noir": "필름 누아르",
    "Chiaroscuro": "키아로스쿠로(명암법)",
    "Rain-slicked": "빗물에 젖은",
    "Technicolor": "테크니컬러",
    "1950s Musical": "1950년대 뮤지컬",
    "Saturated Dream": "채도가 높은 꿈",
    "Spaghetti Western": "스파게티 웨스턴",
    "Dusty Ochre": "먼지 낀 황토색",
    "Sun-bleached": "햇볕에 바랜",
    "Analog Horror": "아날로그 호러",
    "VHS Lo-Fi": "VHS 로파이",
    "Grainy Terror": "거친 공포",
    "Indian Sari": "인도 사리",
    "Kanjivaram Silk": "칸지바람 실크",
    "Zari Gold": "자리 골드",
    "Persian Rug": "페르시아 양탄자",
    "Islamic Geometric": "이슬람 기하학",
    "Arabesque": "아라베스크",
    "Chinese Porcelain": "중국 도자기",
    "Ming Cobalt": "명나라 코발트",
    "Translucent Glaze": "반투명 유약",
    "Scottish Tartan": "스코틀랜드 타탄",
    "Twill Weave": "트윌 직조",
    "Highland Wool": "하이랜드 울",
    "Japanese Sashiko": "일본 사시코",
    "Boro Indigo": "보로 인디고",
    "Wabi-Sabi Stitch": "와비사비 스티치",
    "Peruvian Alpaca": "페루 알파카",
    "Andean Geometric": "안데스 기하학",
    "Sacred Valley": "신성한 계곡",
    "Aurora Borealis": "오로라",
    "Ethereal Light": "천상의 빛",
    "Fluid Gradient": "유동적 그라데이션",
    "Supercell Storm": "슈퍼셀 폭풍",
    "Tornado Vortex": "토네이도 소용돌이",
    "Ominous Gray": "불길한 회색",
    "Coral Reef": "산호초",
    "Bioluminescent Sea": "발광 바다",
    "Pulsating Neon": "맥동하는 네온",
    "Saharan Sandstorm": "사하라 모래폭풍",
    "Haboob": "하부브(모래폭풍)",
    "Lightning Flux": "번개 플럭스",
    "Electric Vein": "전기 맥",
    "Piercing White": "찌르는 듯한 흰색",
    "Geyser Hot Spring": "간헐천 온천",
    "Mineral Crust": "광물 껍질",
    "Sulfur Steam": "유황 증기",
    "Autumn Peak": "가을 절정",
    "Crisp Maple": "바삭한 단풍",
    "Golden Sunlight": "황금빛 햇살",
    "Sakura Bloom": "벚꽃 만개",
    "Soft Petal": "부드러운 꽃잎",
    "Romantic Serenity": "로맨틱한 평온",
    "Hydrothermal Abyss": "열수 심연",
    "Tubeworm Focus": "관벌레 초점",
    "Extreme Resilience": "극한의 회복력",
    "Glacial Calving": "빙하 분리",
    "Fractured Ice": "갈라진 얼음",
    "Titanic Blue": "타이타닉 블루",
    "Cell Microbiology": "세포 미생물학",
    "Lipid Membrane": "지질 막",
    "Vital Flow": "생명 흐름",
    "Cosmic Nebula": "우주 성운",
    "Magellanic Gas": "마젤란 가스",
    "Stardust Gold": "별가루 골드",
    "Amethyst Geode": "자수정 정동",
    "Geometric Facets": "기하학적 면",
    "Crystal Refraction": "수정 굴절",
    "PCB Circuits": "PCB 회로",
    "Gold Trace": "골드 트레이스",
    "Technical Precision": "기술적 정밀도",
    "Liquid Marble": "액체 대리석",
    "Swirl Vein": "소용돌이 결",
    "Luxurious Flow": "고급스러운 흐름",
    "Fractal Mandelbrot": "프랙탈 만델브로",
    "Recursive Geometry": "재귀 기하학",
    "Infinite Depth": "무한한 깊이",
    "X-Ray Skeletal": "엑스레이 골격",
    "Translucent": "반투명",
    "Clinical Monochrome": "임상 모노크롬",
    "Radioactive Glow": "방사능 발광",
    "Uranium Glass": "우라늄 유리",
    "Toxic Neon": "유독성 네온",
    "Ink Diffusion": "잉크 확산",
    "Milky Water": "우유 빛 물",
    "Ethereal Swirl": "천상의 소용돌이",
    "Sound Cymatics": "소리 진동(사이매틱스)",
    "Geometric Sand": "기하학적 모래",
    "Harmonic Ripple": "조화로운 파문",
    "Molten Glass": "녹은 유리",
    "Viscous Heat": "점성 열",
    "Artisanal Glow": "장인의 빛",
    "Carbon Fiber": "탄소 섬유",
    "High-Tech Weave": "하이테크 직조",
    "Stealth Performance": "스텔스 성능",
    "Apple Minimalism": "애플 미니멀리즘",
    "Aluminum Unibody": "알루미늄 유니바디",
    "Frictionless": "마찰 없는",
    "Nintendo Playful": "닌텐도 플레이풀",
    "Chunky Plastic": "두툼한 플라스틱",
    "Primary Fun": "원초적인 재미",
    "Tesla Cyber-Futurism": "테슬라 사이버 미래주의",
    "Cold Steel": "차가운 강철",
    "Hermès Heritage": "에르메스 헤리티지",
    "Epsom Leather": "앱송 가죽",
    "Quiet Luxury": "조용한 럭셔리",
    "Dyson Engineering": "다이슨 엔지니어링",
    "Transparent Polycarb": "투명 폴리카보네이트",
    "Radical High-Tech": "급진적 하이테크",
    "LEGO Modular": "레고 모듈러",
    "Studded Plastic": "스터드 플라스틱",
    "Primary Brights": "원색의 밝음",
    "Coca-Cola Vintage": "코카콜라 빈티지",
    "Spencerian Red": "스펜서리안 레드",
    "Amber Glass": "호박색 유리",
    "Vogue Editorial": "보그 에디토리얼",
    "High-Fashion": "하이패션",
    "Stark Monochrome": "황량한 모노크롬",
    "National Geographic": "내셔널 지오그래픽",
    "Yellow Frame": "노란색 프레임",
    "Explorer Authentic": "탐험가의 진정성",
    "IKEA Nordic": "이케아 노르딕",
    "Light Wood": "밝은 나무",
    "Hygge Functional": "휘게 기능주의",
    "Star Wars": "스타워즈",
    "Used Future": "오래된 미래",
    "Grimy Industrial": "더러운 산업",
    "Marvel Heroic": "마블 영웅적",
    "Dynamic Energy": "역동적 에너지",
    "Cinematic Legend": "영화적 전설",
    
    # Existing Japanese Translations (Already mapped but good for safety)
    "クリエイティブ": "창의적",
    "ラフ": "러프한",
    "個人的": "개인적",
    "ブレインストーミング": "브레인스토밍",
    "本物": "진정성 있는",
    "フレンドリー": "친근한",
    "プロフェッショナル": "전문적",
    "信頼できる": "신뢰할 수 있는",
    "モダン": "모던한",
    "インクルーシブ": "포용적",
    "情報的": "정보 중심",
    "遊び心": "장난기",
    "明快": "명확한",
    "乙女チック": "소녀감성",
    "恋": "사랑",
    "夢": "꿈",
    "少女漫画": "순정만화",
    "キラキラ": "반짝반짝",
    "親近感": "친근감",
    "手作り": "핸드메이드",
    "カフェ": "카페",
    "日常": "일상",
    "素朴": "소박한",
    "童話": "동화",
    "楽しい": "즐거운",
    "柔らかい": "부드러운",
    "アナログ": "아날로그",
    "極小": "극소",
    "透明": "투명한",
    "純粋": "순수한",
    "繊細": "섬세한",
    "可愛い": "귀여운",
    "箱庭": "모형 정원",
    "玩具": "장난감",
    "俯瞰": "내려다보는 시점(부감)",
    "非現実": "비현실적",
    "計画": "계획",
    "設計": "설계",
    "工業的": "공업적",
    "精密": "정밀한",
    "知的": "지적인",
    "誠実": "성실한",
    "洗練": "세련된",
    "静謐": "조용한",
    "シンプル": "심플한",
    "静寂": "정적",
    "モード": "모드",
    "大人": "어른스러운",
    "冒険": "모험",
    "物語": "이야기",
    "古風": "고풍스러운",
    "想像力": "상상력",
    "親しみやすい": "친숙한",
    "ポジティブ": "긍정적",
    "日常的": "일상적인",
    "汎用的": "범용적인",
    "和モダン": "일본 모던",
    "粋": "멋",
    "大胆": "대담한",
    "伝統と革新": "전통과 혁신",
    "豪華": "호화로운",
    "優雅": "우아한",
    "クラシックモダン": "클래식 모던",
    "幾何学的": "기하학적",
    "ラグジュアリー": "럭셔리",
    "神秘的": "신비로운",
    "高価": "값비싼",
    "ドラマチック": "드라마틱한",
    "タイムレス": "시대를 초월한",
    "エレガント": "엘레강스한",
    "伝統的": "전통적인",
    "禅": "젠(선)",
    "力強い": "힘찬",
    "和風": "일본풍",
    "伝統": "전통",
    "迫力": "박력",
    "ジャポニズム": "자포니즘",
    "インディー": "인디",
    "アート": "아트",
    "印刷": "인쇄",
    "レトロ": "레트로",
    "味がある": "풍취 있는",
    "高級": "고급",
    "冷涼": "서늘한",
    "クラシック": "클래식",
    "近未来": "근미래",
    "清潔": "청결한",
    "ソフト": "소프트",
    "ミニマル": "미니멀",
    "空間": "공간",
    "本質": "본질",
    "魂": "영혼",
    "夜": "밤",
    "都市": "도시",
    "孤独": "고독",
    "鮮烈": "강렬한",
    "サイバーパンク": "사이버펑크",
    "ナイトライフ": "나이트 라이프",
    "レトロフューチャー": "레트로 퓨처",
    "誘惑": "유혹",
    "光": "빛",
    "都会": "도회적",
    "映画的": "영화적",
    "雨": "비",
    "リラックス": "릴랙스",
    "メランコリック": "멜랑콜리",
    "快適": "쾌적한",
    "構成主義": "구성주의",
    "バランス": "밸런스",
    "レトロモダン": "레트로 모던",
    "冷徹": "냉철한",
    "グリッド": "그리드",
    "ネットワーク": "네트워크",
    "未来": "미래",
    "知性": "지성",
    "ハイテク": "하이테크",
    "ＳＦ": "SF",
    "情報": "정보",
    "半透明": "반투명",
    "知的、計画的、精密、エンジニアリング": "지적, 계획적, 정밀, 엔지니어링",
    "工業": "공업",
    "技術的": "기술적",
    "機能的": "기능적",
    "無骨": "투박한",
    "モダン建築": "모던 건축",
    "クリーン": "클린",
    "明るい": "밝은",
    "インパクト": "임팩트",
    "怪談": "괴담",
    "恐怖": "공포",
    "夏": "여름",
    "幽玄": "유현한",
    "開放的": "개방적",
    "爽やか": "상쾌한",
    "リゾート": "리조트",
    "浮遊感": "부유감",
    "清涼": "청량한",
    "神秘": "신비",
    "深い": "깊은",
    "デジタル": "디지털",
    "穏やか": "평온한",
    "幾何学": "기하학",
    "楽観的": "낙관적",
    "テクノロジー": "테크놀로지",
    "エコロジー": "생태적",
    "2000s": "2000년대",
    "近未来（過去から見た）": "근미래 (과거 시점)",
    "サイバー": "사이버",
    "有機的": "유기적",
    "未来的": "미래지향적",
    "流動的": "유동적",
    "冷たい": "차가운",
    "歪み": "왜곡",
    "滑らか": "매끄러운",
    "プレミアム": "프리미엄",
    "子供向け": "어린이용",
    "優しい": "상냥한",
    "手作り感": "핸드메이드 느낌",
    "立体": "입체",
    "ファンシー": "팬시",
    "温かい": "따뜻한",
    "落ち着き": "차분함",
    "クラフト感": "크래프트 감각",
    "童話的": "동화적",
    "立体的": "입체적",
    "報道": "보도",
    "重大": "중대한",
    "権威": "권위",
    "革命的": "혁명적",
    "扇動的": "선동적",
    "ダイナミック": "다이내믹",
    "革命": "혁명",
    "力": "힘",
    "ポスター": "포스터",
    "緊急": "긴급",
    "危険": "위험",
    "サイバー攻撃": "사이버 공격",
    "暗号": "암호",
    "緊迫": "긴박한",
    "哀愁": "애수",
    "成熟": "성숙한",
    "豊穣": "풍요로운",
    "暖かい": "따뜻한",
    "自然": "자연",
    "癒やし": "치유",
    "生命力": "생명력",
    "新鮮": "신선한",
    "論理的": "논리적",
    "開発者": "개발자",
    "マトリックス": "매트릭스",
    "システム": "시스템",
    "北欧": "북유럽",
    "暮らし": "생활",
    "おしゃれ": "세련된",
    "自然体": "자연스러운",
    "瞑想的": "명상적",
    "精神的": "정신적",
    "侘び寂び": "와비사비",
    "古代": "고대",
    "堅牢": "견고한",
    "複雑": "복잡한",
    "歴史的": "역사적",
    "不吉": "불길한",
    "古代的": "고대풍",
    "崇高": "숭고한",
    "神聖": "신성한",
    "荘厳": "장엄한",
    "カラフル": "컬러풀",
    "歴史": "역사",
    "格調高い": "격조 높은",
    "芸術的": "예술적",
    "重厚": "중후한",
    "高級感": "고급감",
    "深淵": "심연",
    "現代的": "현대적",
    "ポップ": "팝",
    "触覚的": "촉각적",
    "デジタルアート": "디지털 아트",
    "ノスタルジック": "노스탤지어",
    "キュート": "큐트",
    "高度": "고도로 발달한",
    "信頼感": "신뢰감",
    "セキュリティ": "보안",
    "전통미": "전통미",
    "섬세": "섬세함",
    "유구": "유구한",
    "시적": "시적인",
    "장식적": "장식적",
    "夢幻的": "몽환적",
    "不条理": "부조리한",
    "深層心理": "심층 심리",
    "驚き": "놀라움",
    "超現実": "초현실",
    "節制": "절제된",
    "秩序": "질서",
    "客観的": "객관적",
    "華麗": "화려한",
    "贅沢": "사치스러운",
    "流線型": "유선형",
    "近代化": "근대화",
    "勝利感": "승리감",
    "温かみ": "온기",
    "手仕事": "수작업",
    "熟成": "숙성된",
    "多層": "다층적",
    "輝き": "광채",
    "肉筆感": "손그림 느낌",
    "劇的": "극적인",
    "情熱": "열정",
    "永遠": "영원한",
    "精緻": "정치한",
    "英雄的": "영웅적",
    "未来志向": "미래 지향적",
    "機能美": "기능미",
    "科学": "과학",
    "産業的": "산업적",
    "宣伝的": "선전용",
    "緊張": "긴장감",
    "監視": "감시",
    "秘密": "비밀",
    "管理": "관리",
    "無機質": "무기질적인",
    "デジタル・サイケデリック": "디지털 사이키델릭",
    "皮肉": "냉소적",
    "80-90s": "80-90년대",
    "ディストピア": "디스토피아",
    "高密度": "고밀도",
    "叛逆": "반역",
    "雑多": "잡다한",
    "合理的": "합리적",
    "普遍的": "보편적",
    "強力": "강력한",
    "郷愁": "향수",
    "平和": "평화",
    "懐かしさ": "그리움",
    "実用的": "실용적",
    "構造的": "구조적",
    "革新": "혁신",
    "非定型": "비정형",
    "精妙": "정묘한",
    "謙虚": "겸허한",
    "芳醇": "향기로운",
    "大地": "대지",
    "閑雅": "한적하고 우아한",
    "発光": "발광",
    "異界": "이계",
    "心地よさ": "안락함",
    "温もり": "따스함",
    "簡素": "간소한",
    "ヒュッゲ": "휘게",
    "無常": "무상함",
    "不完全の美": "불완전의 미",
    "瞑想": "명상",
    "活気": "활기",
    "躍動": "역동",
    "文化的": "문화적",
    "物語的": "서사적",
    "畏怖": "경외심",
    "生々しい": "생생한",
    "反逆的": "반항적",
    "アヴァンギャルド": "아방가르드",
    "異国情緒": "이국 정서",
    "豊か": "풍부한",
    "詳細": "상세한",
    "科学的": "과학적",
    "自然美": "자연미",
    "空想的": "공상적",
    "1960s": "1960년대",
    "極寒": "극한의 추위",
    "広大": "광대한",
    "結晶": "결정",
    "静止": "정지된",
    "日差し": "햇살",
    "鮮やか": "선명한",
    "憧れ": "동경",
    "機械的": "기계적",
    "ヴィンテージ": "빈티지",
    "石炭の匂い": "석탄 냄새",
    "乾いた温かみ": "메마른 온기",
    "高出力": "고출력",
    "電気的": "전기적",
    "多層的": "다층적",
    "喧騒": "떠들썩함",
    "没入型": "몰입형",
    "魔法": "마법",
    "孤高": "고고한",
    "彩度低め": "저채도",
    "憂鬱": "우울",
    "謎": "수수께끼",
    "記念碑的": "기념비적",
    "象徴的": "상징적",
    "緻密": "치밀한",
    "数学的": "수학적",
    "黄金時代": "황금 시대",
    "臨床的": "임상적",
    "生命維持": "생명 유지",
    "極限": "극한",
    "高圧": "고압",
    "異質": "이질적",
    "野生的": "야생적",
    "圧倒的": "압도적",
    "冬の太陽": "겨울 태양",
    "不安": "불안",
    "魅惑": "매혹",
    "混濁": "혼탁",
    "自己進化": "자기 진화",
    "実験的": "실험적",
    "原始的": "원시적",
    "圧迫的": "압박감",
    "高熱": "고열",
    "極限のコントラスト": "극한의 대비",
    "悠久": "유구한",
    "空중": "공중",
    "변덕스러운": "변덕스러운",
    "기술적 세련미": "기술적 세련미",
    "낭만": "낭만",
    "冷酷": "냉혹한",
    "毒性": "독성",
    "産業的廃墟": "산업 폐허",
    "化学的崩壊": "화학적 붕괴",
    "合成的": "합성적",
    "刹那的": "찰나적",
    "사이버네틱": "사이버네틱",
    "規律": "규율",
    "ハイテク伝統主義": "하이테크 전통주의",
    "静謐": "정밀",
    "鋭利": "예리한",
    "生物的": "생물학적",
    "攻撃的": "공격적",
    "虹色": "무지개빛",
    "抽象的": "추상적",
    "精力的": "정력적",
    "予測不能": "예측 불가능",
    "多次元": "다차원",
    "振動": "진동",
    "荒涼": "황량한",
    "苛酷": "가혹한",
    "産業的生存": "산업적 생존",
    "埃っぽい": "먼지 투성이",
    "人形のような": "인형 같은",
    "過度な装飾": "과도한 장식",
    "脆弱": "취약함",
    "幻想的": "환상적",
    "持続可能": "지속 가능",
    "調和": "조화",
    "ムーディー": "분위기 있는",
    "冷笑的": "냉소적",
    "都市の孤独": "도시의 고독",
    "緊迫した謎": "긴장된 수수께끼",
    "陰影": "음영",
    "超現実的": "초현실적",
    "演劇的": "연극적",
    "壮大": "장대한",
    "無骨": "거친",
    "復讐心": "복수심",
    "日干しの": "햇볕에 말린",
    "不気味": "으스스한",
    "謎めいた": "수수께끼 같은",
    "歪んだ": "왜곡된",
    "低解像度": "저해상도",
    "威厳": "위엄",
    "祝祭": "축제",
    "無限": "무한",
    "時代を超越した": "시대를 초월한",
    "繊細": "섬세",
    "高貴": "고귀한",
    "素朴": "소박",
    "耐久性": "내구성",
    "忍耐": "인내",
    "繕い": "수선",
    "積層": "적층",
    "先祖代々の": "선조 대대로의",
    "地理的": "지리적",
    "濃厚": "농후한",
    "天体的": "천체적",
    "不穏": "불온한",
    "脈動": "맥동",
    "荒々しい": "거친",
    "単一的": "단일적",
    "包み込む": "감싸는",
    "粒子感": "입자감",
    "高エネルギー": "고에너지",
    "瞬間的": "순간적",
    "貫通": "관통",
    "衝撃": "충격",
    "癒し": "치유",
    "揮発的": "휘발성",
    "化学的美": "화학적 미",
    "強靭": "강인한",
    "モノクローム": "모노크롬",
    "脆弱": "취약",
    "巨大": "거대한",
    "生命的": "생명적",
    "透明感": "투명감",
    "内部光": "내부 발광",
    "広大": "광대함",
    "放射": "방사",
    "野生的": "야생성",
    "屈折": "굴절",
    "貴重": "귀중한",
    "連結": "연결",
    "予測不可能": "예측 불가",
    "催眠的": "최면적",
    "反復的": "반복적",
    "啓示的": "계시적",
    "幽霊のような": "유령 같은",
    "気味悪い": "기분 나쁜",
    "幻覚的": "환각적",
    "束の間": "잠깐의",
    "柔らか": "부드러움",
    "湧き上がる": "솟아오르는",
    "詩的": "시적",
    "浄化": "정화",
    "模様": "무늬",
    "共鳴": "공명",
    "強烈": "강렬",
    "職人的": "장인적",
    "粘性": "점성",
    "白熱": "백열",
    "創造の瞬間": "창조의 순간",
    "性能": "성능",
    "強度": "강도",
    "軽量": "경량",
    "隠密": "은밀함",
    "純수": "순수",
    "필수적": "필수적",
    "마찰 없음": "마찰 없음",
    "단순화된 인지": "단순화된 인지",
    "愉快": "유쾌",
    "접근성": "접근성",
    "덩어리감": "덩어리감",
    "상상력": "상상력",
    "무구한 재미": "순수한 재미",
    "브루탈리즘": "브루탈리즘",
    "냉혹": "냉혹",
    "파괴적": "파괴적",
    "실용적": "실용적",
    "고집스러운 미니멀리즘": "고집스러운 미니멀리즘",
    "장인정신": "장인정신",
    "승마 기반": "승마 기반",
    "정교": "정교함",
    "조용한 럭셔리": "조용한 럭셔리",
    "고성능": "고성능",
    "급진적": "급진적",
    "투명성": "투명성",
    "기능 중심": "기능 중심",
    "미래 전자": "미래 전자",
    "연물 교합": "연물 교합(클러치)",
    "향수": "향수",
    "모듈형": "모듈형",
    "축제": "축제",
    "사교적": "사교적",
    "클래식한 상쾌함": "클래식한 상쾌함",
    "아메리카나": "아메리카나",
    "전위적": "전위적",
    "냉정": "냉정",
    "권위적": "권위적",
    "대담": "대담",
    "고대비": "고대비",
    "탐험적": "탐험적",
    "진실성": "진실성",
    "서사적": "서사적",
    "교육적": "교육적",
    "강렬한 자연": "강렬한 자연",
    "정직": "정직",
    "평등": "평등",
    "밝음": "밝음",
    "휘게(Hygge)": "휘게(Hygge)",
    "민주적 디자인": "민주적 디자인",
    "마모됨": "마모됨",
    "거침": "거침",
    "생활감": "생활감",
    "오래된 첨단": "오래된 첨단",
    "역동적": "역동적",
    "임팩트": "임팩트",
    "전설적": "전설적",
    "시네마틱": "시네마틱",
    "거대한 스케일": "거대한 스케일" 
}

def translate_batch():
    with open('templates.json', 'r', encoding='utf-8') as f:
        data = json.load(f)

    styles = data.get('styles_001_100', [])
    updated_count = 0

    for item in styles:
        elab = item.get('elaboration', '')
        # Basic cleanup first
        elab = elab.replace('Migrated from legacy: ', '')
        
        # Split by comma or Japanese comma
        tokens = re.split(r'[,、]', elab)
        new_tokens = []
        changes_made = False
        
        for t in tokens:
            t = t.strip().rstrip('。').rstrip('.')
            if not t: continue
            
            # Direct map check
            if t in TRANSLATION_MAP:
                new_tokens.append(TRANSLATION_MAP[t])
                changes_made = True
            else:
                # Case insensitive check for English
                found = False
                for k, v in TRANSLATION_MAP.items():
                    if k.lower() == t.lower():
                        new_tokens.append(v)
                        found = True
                        changes_made = True
                        break
                if not found:
                    new_tokens.append(t) # Keep original if no match
        
        if changes_made:
            item['elaboration'] = ", ".join(new_tokens)
            updated_count += 1
            
    print(f"Batch translation complete. Updated {updated_count} items.")
    
    with open('templates.json', 'w', encoding='utf-8') as f:
        json.dump(data, f, indent=2, ensure_ascii=False)

if __name__ == "__main__":
    translate_batch()
