import json
import re

# Expanded Dictionary based on the patterns seen
TRANSLATION_MAP = {
    "。": ".",
    "、": ", ",
    "「": "\"",
    "」": "\"",
    "・": " / ",
    
    # Common words found in Japanese design descriptions
    "雰囲気": "Atmosphere",
    "スタイル": "Style",
    "特徴": "Features",
    "構成": "Composition",
    "背景色": "Background Color",
    "文字色": "Text Color",
    "アクセントカラー": "Accent Color",
    "見出し": "Headers",
    "質感": "Texture",
    "形状": "Shapes",
    "照明": "Lighting",
    "色数": "Colors",
    "要素": "Elements",
    "効果": "Effects",
    
    # Adjectives & Nouns
    "クリエイティブ": "Creative",
    "ラフ": "Rough",
    "個人的": "Personal",
    "ブレインストーミング": "Brainstorming",
    "本物": "Authentic",
    "罫線入りノート用紙": "Lined Notebook Paper",
    "方眼紙": "Graph Paper",
    "手書き": "Handwritten",
    "美学": "Aesthetic",
    "棒人間": "Stick Figures",
    "星": "Stars",
    "矢印": "Arrows",
    "コーヒーの染み": "Coffee Stains",
    "余白": "Whitespace",
    "書き込み": "Scribbles",
    "自由形式": "Freeform",
    "フォント": "Font",
    "乱雑な": "Messy",
    "走り書き": "Scrawl",
    "下線付き": "Underlined",
    "モダン": "Modern",
    "フレンドリー": "Friendly",
    "プロフェッショナル": "Professional",
    "信頼できる": "Trustworthy",
    "インクルーシブ": "Inclusive",
    "白": "White",
    "淡い": "Pale",
    "パステルグレー": "Pastel Gray",
    "フラットな": "Flat",
    "ベクター": "Vector",
    "遊び心のある": "Playful",
    "波線": "Wavy Lines",
    "ドット": "Dots",
    "三角形": "Triangles",
    "有機的な": "Organic",
    "人物": "People",
    "単純化された": "Simplified",
    "バランスの取れた": "Balanced",
    "三分割法": "Rule of Thirds",
    "十分な": "Ample",
    "幾何学的": "Geometric",
    "クリーン": "Clean",
    "可読性重視": "High Readability",
    "情報の": "Informational",
    "明快": "Clear",
    "透明": "Transparent",
    "純粋": "Pure",
    "繊細": "Delicate",
    "乙女チック": "Girly",
    "恋": "Love",
    "夢": "Dream",
    "少女漫画": "Shojo Manga",
    "キラキラ": "Sparkle",
    "親近感": "Friendly/Familiar",
    "手作り": "Handmade",
    "カフェ": "Cafe",
    "日常": "Daily Life",
    "素朴": "Rustic/Simple",
    "黒板": "Blackboard",
    "童話": "Fairy Tale",
    "楽しい": "Fun",
    "柔らかい": "Soft",
    "アナログ": "Analog",
    "粘土": "Clay",
    "極小": "Minimal",
    "箱庭": "Miniature Garden",
    "玩具": "Toy",
    "俯瞰": "Bird's eye view",
    "非現実": "Surreal",
    "計画": "Plan/Blueprint",
    "設計": "Design",
    "工業的": "Industrial",
    "精密": "Precision",
    "知的": "Intellectual",
    "誠実": "Sincere",
    "洗練": "Sophisticated",
    "静謐": "Quiet",
    "静寂": "Silence",
    "モード": "Mode/Fashion",
    "大人": "Adult/Mature",
    "冒険": "Adventure",
    "物語": "Story",
    "古風": "Old Fashioned",
    "想像力": "Imagination",
    "親しみやすい": "Approachable",
    "ポジティブ": "Positive",
    "日常的": "Everyday",
    "汎用的": "Versatile",
    "和モダン": "Japanese Modern",
    "粋": "Chic/Iki",
    "大胆": "Bold",
    "伝統と革新": "Tradition & Innovation",
    "豪華": "Luxury",
    "優雅": "Elegant",
    "クラシックモダン": "Classic Modern",
    "神秘的": "Mysterious",
    "高価": "Expensive",
    "ドラマチック": "Dramatic",
    "タイムレス": "Timeless",
    "和風": "Japanese Style",
    "迫力": "Impact/Power",
    "ジャポニズム": "Japonism",
    "インディー": "Indie",
    "アート": "Art",
    "印刷": "Print",
    "味がある": "Tasteful/Character",
    "高級": "High Class",
    "冷涼": "Cool",
    "クラシック": "Classic",
    "近未来": "Near Future",
    "清潔": "Clean/Hygenic",
    "ソフト": "Soft",
    "哲学": "Philosophy",
    "朝": "Morning",
    "空間": "Space",
    "本質": "Essence",
    "魂": "Soul",
    "夜": "Night",
    "都市": "City",
    "孤独": "Solitude",
    "鮮烈": "Vivid",
    "サイバーパンク": "Cyberpunk",
    "ナイトライフ": "Nightlife",
    "レトロフューチャー": "Retro Future",
    "誘惑": "Temptation",
    "光": "Light",
    "都会": "Urban",
    "映画的": "Cinematic",
    "雨": "Rain",
    "リラックス": "Relax",
    "メランコリック": "Melancholic",
    "快適": "Comfortable",
    "構成主義": "Constructivism",
    "冷徹": "Cold/Dispassionate",
    "グリッド": "Grid",
    "ネットワーク": "Network",
    "知性": "Intelligence",
    "計画的": "Planned",
    "エンジニアリング": "Engineering",
    "なし": "None",
    "あり": "Yes",
    "完全な": "Complete",
    "闇": "Darkness",
    "発光色": "Luminous Color",
    "青": "Blue",
    "赤": "Red",
    "黄": "Yellow",
    "緑": "Green",
    "金": "Gold",
    "銀": "Silver",
    "墨": "Ink",
    "和紙": "Washi",
    "生成り": "Ecru",
    "朱色": "Vermilion",
    "藍色": "Indigo",
    "日本語": "Japanese",
    "完全対応した": "Fully Compatible",
    "使用し": "Using",
    "最大精度で描写する": "Draw with maximum precision"
}

def translate_recursive(data):
    if isinstance(data, dict):
        return {k: translate_recursive(v) for k, v in data.items()}
    elif isinstance(data, list):
        return [translate_recursive(item) for item in data]
    elif isinstance(data, str):
        text = data
        # Check if text contains Japanese
        if re.search(r'[\u3000-\u303f\u3040-\u309f\u30a0-\u30ff\uff00-\uff9f\u4e00-\u9faf]', text):
            for jp, en in TRANSLATION_MAP.items():
                text = text.replace(jp, en)
        return text
    else:
        return data

def process_translation():
    with open('templates.json', 'r', encoding='utf-8') as f:
        data = json.load(f)
        
    translated = translate_recursive(data)
        
    with open('templates.json', 'w', encoding='utf-8') as f:
        json.dump(translated, f, indent=2, ensure_ascii=False)
        print("Database translation complete.")

if __name__ == "__main__":
    process_translation()
